import type { Suggestion } from './suggestion.types'

export const suggestionMocks: Suggestion[] = [
  {
    id: 'suggestion-001',
    paperId: 'paper-001',
    extractionId: 'extraction-001',
    action: 'addConcept',
    status: 'pending',
    title: '新增概念：反转学习',
    reason: '论文将反转学习作为核心教学策略进行了明确讨论。',
    confidence: 0.91,
    evidence: [
      {
        id: 'evidence-001',
        paperId: 'paper-001',
        section: 'Introduction',
        text: '反转学习将知识传授移至课前，并把课堂时间用于讨论与问题解决。',
      },
    ],
    candidates: [
      {
        id: 'concept-existing-flipped-classroom',
        kind: 'existing',
        entityType: 'concept',
        targetEntityId: 'concept-flipped-classroom',
        name: '翻转课堂',
        originalName: '翻转课堂',
        confidence: 0.86,
      },
      {
        id: 'concept-existing-blended-learning',
        kind: 'existing',
        entityType: 'concept',
        targetEntityId: 'concept-blended-learning',
        name: '混合学习',
        originalName: '混合学习',
        confidence: 0.63,
      },
      {
        id: 'concept-new-inverted-learning',
        kind: 'new',
        entityType: 'concept',
        targetEntityId: null,
        name: '反转学习',
        originalName: '反转学习',
        confidence: 0.72,
      },
      {
        id: 'concept-existing-classroom-teaching',
        kind: 'existing',
        entityType: 'concept',
        targetEntityId: 'concept-classroom-teaching',
        name: '课堂教学',
        originalName: '课堂教学',
        confidence: 0.41,
      },
    ],
    proposedChange: { name: '反转学习' },
    reviewedAt: null,
    reviewComment: null,
    createdAt: '2026-08-26T09:00:00Z',
    updatedAt: '2026-08-26T09:00:00Z',
  },
  {
    id: 'suggestion-002',
    paperId: 'paper-001',
    extractionId: 'extraction-001',
    action: 'addMethod',
    status: 'pending',
    title: '新增方法：行为任务',
    reason: '论文描述了用于测量学习效果的行为实验任务。',
    confidence: 0.84,
    evidence: [
      {
        id: 'evidence-002',
        paperId: 'paper-001',
        section: 'Methods',
        text: '参与者完成包含四十次试次的行为任务，正确率和反应时间被同步记录。',
      },
    ],
    candidates: [
      {
        id: 'method-existing-behavioral-task',
        kind: 'existing',
        entityType: 'method',
        targetEntityId: 'method-behavioral-task',
        name: '行为任务',
        originalName: '行为任务',
        confidence: 0.84,
      },
      {
        id: 'method-existing-choice-task',
        kind: 'existing',
        entityType: 'method',
        targetEntityId: 'method-choice-task',
        name: '选择反应任务',
        originalName: '选择反应任务',
        confidence: 0.67,
      },
      {
        id: 'method-new-forty-trial-task',
        kind: 'new',
        entityType: 'method',
        targetEntityId: null,
        name: '四十试次行为任务',
        originalName: '四十试次行为任务',
        confidence: 0.76,
      },
    ],
    proposedChange: { name: '行为任务', trialCount: 40 },
    reviewedAt: null,
    reviewComment: null,
    createdAt: '2026-08-26T09:02:00Z',
    updatedAt: '2026-08-26T09:02:00Z',
  },
  {
    id: 'suggestion-005',
    paperId: 'paper-003',
    extractionId: 'extraction-003',
    action: 'addFinding',
    status: 'pending',
    title: '新增发现：学习成绩提升',
    reason: '实验组的测验成绩显著高于对照组。',
    confidence: 0.88,
    evidence: [
      {
        id: 'evidence-005',
        paperId: 'paper-003',
        section: 'Results',
        text: '与对照组相比，实验组的测验正确率提高了 12.4%。',
      },
    ],
    proposedChange: {
      statement: '反转学习组的测验正确率高于对照组',
      effect: 0.124,
    },
    reviewedAt: null,
    reviewComment: null,
    createdAt: '2026-08-26T09:10:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
  {
    id: 'suggestion-006',
    paperId: 'paper-003',
    extractionId: 'extraction-003',
    action: 'addMethod',
    status: 'pending',
    title: '新增方法：状态空间分析',
    reason: '论文使用状态空间方法描述工作记忆活动的时间演化。',
    confidence: 0.82,
    evidence: [
      {
        id: 'evidence-006',
        paperId: 'paper-003',
        section: 'Methods',
        text: '神经群体活动被投影到低维状态空间，以比较不同记忆阶段的动力学轨迹。',
      },
    ],
    candidates: [
      {
        id: 'method-existing-state-space',
        kind: 'existing',
        entityType: 'method',
        targetEntityId: 'method-state-space-analysis',
        name: '状态空间分析',
        originalName: '状态空间分析',
        confidence: 0.82,
      },
      {
        id: 'method-new-neural-trajectory',
        kind: 'new',
        entityType: 'method',
        targetEntityId: null,
        name: '神经轨迹分析',
        originalName: '神经轨迹分析',
        confidence: 0.71,
      },
    ],
    proposedChange: { name: '状态空间分析' },
    reviewedAt: null,
    reviewComment: null,
    createdAt: '2026-08-26T09:12:00Z',
    updatedAt: '2026-08-26T09:12:00Z',
  },
  {
    id: 'suggestion-accepted-001',
    paperId: 'paper-001',
    extractionId: 'extraction-001',
    action: 'addFinding',
    status: 'accepted',
    title: '新增发现：规则切换后反应变慢',
    reason: '行为结果显示规则切换带来了稳定的切换成本。',
    confidence: 0.9,
    evidence: [
      {
        id: 'evidence-accepted-001',
        paperId: 'paper-001',
        section: 'Results',
        text: '规则切换试次的平均反应时间显著长于规则重复试次。',
      },
    ],
    proposedChange: { statement: '规则切换会增加反应时间' },
    reviewedAt: '2026-08-28T09:20:00Z',
    reviewComment: null,
    createdAt: '2026-08-26T09:15:00Z',
    updatedAt: '2026-08-28T09:20:00Z',
  },
  {
    id: 'suggestion-rejected-001',
    paperId: 'paper-001',
    extractionId: 'extraction-001',
    action: 'addRelation',
    status: 'rejected',
    title: '新增关系：前额叶活动预测正确率',
    reason: '模型检测到前额叶信号与任务正确率之间的潜在关系。',
    confidence: 0.61,
    evidence: [
      {
        id: 'evidence-rejected-001',
        paperId: 'paper-001',
        section: 'Discussion',
        text: '前额叶活动与正确率呈弱相关，但该结果未通过多重比较校正。',
      },
    ],
    proposedChange: {
      sourceId: 'concept-prefrontal-activity',
      targetId: 'concept-accuracy',
      relationType: 'predicts',
    },
    reviewedAt: '2026-08-28T09:30:00Z',
    reviewComment: '证据不足，相关结果未通过多重比较校正',
    createdAt: '2026-08-26T09:18:00Z',
    updatedAt: '2026-08-28T09:30:00Z',
  },
]
