import type { PaperDetail } from './paper.types'

/** 模拟 GET /api/v1/papers/{paperId} 返回的论文详情。 */
export const paperDetailMocks: PaperDetail[] = [
  {
    id: 'paper-001',
    title: '反转学习中的认知灵活性与前额叶活动',
    authors: [
      {
        id: 'author-li-ming',
        name: '李明',
        affiliation: '示例大学脑科学中心',
        orcid: null,
      },
      { id: 'author-wang-fang', name: '王芳', affiliation: null, orcid: null },
    ],
    year: 2025,
    doi: '10.1000/yzt.2025.001',
    abstract: '本研究考察反转学习中的行为调整及其神经电生理指标。',
    source: { type: 'manual', externalId: null, url: null },
    status: 'pendingReview',
    latestJobId: 'job-001',
    latestExtractionId: 'extraction-001',
    pendingSuggestionCount: 2,
    researchOverview: {
      researchTopics: ['反转学习', '认知灵活性', '脑电'],
      researchQuestion: '反馈相关神经信号能否预测规则变化后的行为调整？',
      sample: '32 名健康成人',
      methods: '概率反转学习任务与脑电记录',
      mainResults: '反馈相关负波幅度可预测规则切换后的行为调整。',
    },
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
  {
    id: 'paper-002',
    title: '价值更新中的网络动力学',
    authors: [
      { id: 'author-li-ming', name: '李明', affiliation: null, orcid: null },
      { id: 'author-wang-fang', name: '王芳', affiliation: null, orcid: null },
      { id: 'author-chen-wei', name: '陈伟', affiliation: null, orcid: null },
    ],
    year: 2024,
    doi: null,
    abstract: '本研究分析预测误差信号与后续选择更新之间的关系。',
    source: { type: 'academicSearch', externalId: 'search-002', url: null },
    status: 'completed',
    latestJobId: 'job-002',
    latestExtractionId: 'extraction-002',
    pendingSuggestionCount: 0,
    researchOverview: {
      researchTopics: ['强化学习', '预测误差'],
      researchQuestion: '预测误差信号是否影响后续选择更新？',
      sample: null,
      methods: '强化学习模型与行为分析',
      mainResults: '预测误差与后续选择更新显著相关。',
    },
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: '2026-08-25T12:00:00Z',
  },
  {
    id: 'paper-003',
    title: '适应性决策的脑电标记',
    authors: [
      { id: 'author-chen-wei', name: '陈伟', affiliation: null, orcid: null },
      { id: 'author-zhao-jing', name: '赵静', affiliation: null, orcid: null },
    ],
    year: 2023,
    doi: null,
    abstract: '本论文正在解析中，研究概览尚未生成。',
    source: { type: 'zotero', externalId: 'zotero-003', url: null },
    status: 'processing',
    latestJobId: 'job-003',
    latestExtractionId: null,
    pendingSuggestionCount: 0,
    researchOverview: null,
    createdAt: '2026-08-26T07:30:00Z',
    updatedAt: '2026-08-26T10:00:00Z',
  },
  {
    id: 'paper-004',
    title: '人类层级强化学习',
    authors: [
      { id: 'author-zhou-ning', name: '周宁', affiliation: null, orcid: null },
      { id: 'author-sun-yue', name: '孙悦', affiliation: null, orcid: null },
    ],
    year: 2022,
    doi: null,
    abstract: null,
    source: { type: 'manual', externalId: null, url: null },
    status: 'failed',
    latestJobId: 'job-004',
    latestExtractionId: null,
    pendingSuggestionCount: 0,
    researchOverview: null,
    createdAt: '2026-08-25T06:00:00Z',
    updatedAt: '2026-08-26T10:05:00Z',
  },
  {
    id: 'paper-005',
    title: '可重复的任务切换数据集',
    authors: [
      { id: 'author-wu-lan', name: '吴兰', affiliation: '开放科学研究中心', orcid: null },
    ],
    year: 2021,
    doi: null,
    abstract: '本研究发布可重复使用的任务切换行为与网络分析数据。',
    source: { type: 'manual', externalId: null, url: null },
    status: 'completed',
    latestJobId: null,
    latestExtractionId: 'extraction-005',
    pendingSuggestionCount: 0,
    researchOverview: {
      researchTopics: ['任务切换', '开放数据'],
      researchQuestion: '标准化数据能否支持任务切换研究的重复分析？',
      sample: '公开示例数据集',
      methods: '任务切换范式与网络分析',
      mainResults: '数据与分析流程可被独立复用。',
    },
    createdAt: '2026-08-18T06:00:00Z',
    updatedAt: '2026-08-24T10:05:00Z',
  },
]
