import type {
  AuthorDetail as AuthorDetailDto,
  PaperDetail as PaperDetailDto,
} from '../../contracts/v05.types'

/** 模拟 GET /api/v1/papers/{paperId} 返回的论文详情。 */
export const paperDetailMocks: PaperDetailDto[] = [
  {
    id: 'paper-001',
    title: '反转学习中的认知灵活性与前额叶活动',
    authors: [
      { authorId: 'author-wang-fang', displayName: '王芳', rawName: 'Wang Fang', authorOrder: 2 },
      { authorId: 'author-li-ming', displayName: '李明', rawName: 'Li Ming', authorOrder: 1 },
    ],
    year: 2025,
    doi: '10.1000/yzt.2025.001',
    journal: {
      name: 'Nature Neuroscience',
      issn: '1097-6256',
      metrics: {
        impactFactor: 25,
        jcrDataYear: 2024,
        categories: [{ category: 'Neurosciences', quartile: 'Q1' }],
        metricSource: 'JCR',
      },
    },
    abstract: '本研究考察反转学习中的行为调整及其神经电生理指标。',
    source: { type: 'manual', externalId: null, url: null },
    status: 'pendingReview',
    latestJobId: 'job-001',
    latestExtractionId: 'extraction-001',
    pendingSuggestionCount: 2,
    researchOverview: {
      researchTopics: ['反转学习', '认知灵活性', '脑电'],
      researchQuestion: '反馈相关神经信号能否预测规则变化后的行为调整？',
      sample: '32 名健康成人',
      methods: '概率反转学习任务与脑电记录',
      mainResults: '反馈相关负波幅度可预测规则切换后的行为调整。',
    },
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
  {
    id: 'paper-002',
    title: '价值更新中的网络动力学',
    authors: [
      { authorId: 'author-chen-wei', displayName: '陈伟', rawName: 'Chen Wei', authorOrder: 3 },
      { authorId: 'author-li-ming', displayName: '李明', rawName: 'Li Ming', authorOrder: 1 },
      { authorId: 'author-wang-fang', displayName: '王芳', rawName: 'Wang Fang', authorOrder: 2 },
    ],
    year: 2024,
    doi: null,
    journal: {
      name: 'Neuron',
      issn: '0896-6273',
      metrics: {
        impactFactor: 16.2,
        jcrDataYear: 2024,
        categories: [{ category: 'Neurosciences', quartile: 'Q1' }],
        metricSource: 'JCR',
      },
    },
    abstract: '本研究分析预测误差信号与后续选择更新之间的关系。',
    source: { type: 'academicSearch', externalId: 'search-002', url: null },
    status: 'completed',
    latestJobId: 'job-002',
    latestExtractionId: 'extraction-002',
    pendingSuggestionCount: 0,
    researchOverview: {
      researchTopics: ['强化学习', '预测误差'],
      researchQuestion: '预测误差信号是否影响后续选择更新？',
      sample: null,
      methods: '强化学习模型与行为分析',
      mainResults: '预测误差与后续选择更新显著相关。',
    },
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: '2026-08-25T12:00:00Z',
  },
  {
    id: 'paper-003',
    title: '适应性决策的脑电标记',
    authors: [
      { authorId: 'author-zhao-jing', displayName: '赵静', rawName: 'Zhao Jing', authorOrder: 2 },
      { authorId: 'author-chen-wei', displayName: '陈伟', rawName: 'Chen Wei', authorOrder: 1 },
    ],
    year: 2023,
    doi: null,
    journal: {
      name: 'Cerebral Cortex',
      issn: '1047-3211',
      metrics: {
        impactFactor: 4.2,
        jcrDataYear: 2024,
        categories: [{ category: 'Neurosciences', quartile: 'Q2' }],
        metricSource: 'JCR',
      },
    },
    abstract: '本论文正在解析中，研究概览尚未生成。',
    source: { type: 'zotero', externalId: 'zotero-003', url: null },
    status: 'processing',
    latestJobId: 'job-003',
    latestExtractionId: null,
    pendingSuggestionCount: 0,
    researchOverview: null,
    createdAt: '2026-08-26T07:30:00Z',
    updatedAt: '2026-08-26T10:00:00Z',
  },
  {
    id: 'paper-004',
    title: '人类层级强化学习',
    authors: [
      { authorId: 'author-zhou-ning', displayName: '周宁', rawName: 'Zhou Ning', authorOrder: 1 },
      { authorId: 'author-sun-yue', displayName: '孙悦', rawName: 'Sun Yue', authorOrder: 2 },
    ],
    year: 2022,
    doi: null,
    journal: null,
    abstract: null,
    source: { type: 'manual', externalId: null, url: null },
    status: 'failed',
    latestJobId: 'job-004',
    latestExtractionId: null,
    pendingSuggestionCount: 0,
    researchOverview: null,
    createdAt: '2026-08-25T06:00:00Z',
    updatedAt: '2026-08-26T10:05:00Z',
  },
  {
    id: 'paper-005',
    title: '可重复的任务切换数据集',
    authors: [
      { authorId: 'author-wu-lan', displayName: '吴兰', rawName: 'Wu Lan', authorOrder: 1 },
    ],
    year: 2021,
    doi: null,
    journal: { name: 'Open Science Journal', issn: null, metrics: null },
    abstract: '本研究发布可重复使用的任务切换行为与网络分析数据。',
    source: { type: 'manual', externalId: null, url: null },
    status: 'completed',
    latestJobId: null,
    latestExtractionId: 'extraction-005',
    pendingSuggestionCount: 0,
    researchOverview: {
      researchTopics: ['任务切换', '开放数据'],
      researchQuestion: '标准化数据能否支持任务切换研究的重复分析？',
      sample: '公开示例数据集',
      methods: '任务切换范式与网络分析',
      mainResults: '数据与分析流程可被独立复用。',
    },
    createdAt: '2026-08-18T06:00:00Z',
    updatedAt: '2026-08-24T10:05:00Z',
  },
]

/** v05 作者详情 DTO Mock；导入的 ORCID 保留来源且不标记为 OAuth 认证。 */
export const authorDetailMocks: AuthorDetailDto[] = [
  {
    id: 'author-li-ming',
    displayName: '李明',
    nameVariants: ['Li Ming'],
    externalIds: {
      orcid: '0000-0002-1825-0097',
      orcidSource: 'crossref',
      orcidAuthenticated: false,
    },
    affiliations: [{
      rawText: '示例大学脑科学中心',
      displayName: '示例大学脑科学中心',
      rorId: null,
    }],
    identityStatus: 'resolved',
    mergedIntoAuthorId: null,
    paperCount: 2,
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
  {
    id: 'author-wang-fang',
    displayName: '王芳',
    nameVariants: ['Wang Fang'],
    externalIds: {
      orcid: '0000-0001-5109-3700',
      orcidSource: 'orcidOAuth',
      orcidAuthenticated: true,
    },
    affiliations: [],
    identityStatus: 'resolved',
    mergedIntoAuthorId: null,
    paperCount: 2,
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
]
